version: 'latest'

services:
  app:
    container_name: testTask
    build: ./
    depends_on:
      - db
    volumes:
      - ./app:/usr/local/src/app
    ports:
      - "8001:8001"
    restart: always
    env_file:
      - .env
    network_mode: bridge


  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - .postgres:/var/lib/postgres/data
    restart: always
    network_mode: bridge